### ISSUE TITLE
To boolean?

### ISSUE THREAD

**Issue by dmitrijsk** [dbampalikis/wumpus_2021#6]
Just an idea - it may simplify things here or in part B.
The book uses boolean `FacingEast`, `FacingNorth`, etc. So maybe replace char with 4 booleans. We will see.

https://github.com/dbampalikis/wumpus_2021/blob/711ac5086b8000ba018aab3b895a7308c70ce917/Wumpus_v1-1/Wumpus_World/src/main/java/fullObservability/SearchAI.java#L18

**Comment by dbampalikis** [comment]
Finally followed the way it was used from the professor
